## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [59]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [60]:
boston=datasets.load_boston()
trainx,testx,trainy,testy=train_test_split(boston.data,boston.target,test_size=0.1)

In [35]:
reg=LinearRegression()


In [38]:
reg.fit(trainx,trainy)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
py_pred = reg.predict(testx)

In [44]:
py_pred

array([18.77017155, 16.99192197, 35.60161842, 31.14027318, 25.39000217,
       20.33684136, 11.40008438, 25.79238848, 38.06584703,  8.37961135,
       24.83160027, 23.90237803, 25.90822266, 11.55623704, 22.66811694,
       26.27388701, 12.90153316,  3.3180812 , 28.78201222, 22.78396451,
       21.04118329, 17.08810867, 37.00531828, 21.25638545,  1.24943838,
       33.62258927, 15.75411756, 19.30335964, 27.38713488, 16.66326536,
       11.37963959, 24.19909296, 32.13313396, 23.87163106, 25.50539214,
       33.10738405, 15.7311403 , 35.85685758, 39.66467609, 27.39015942,
       27.930623  , 28.21404357, 18.86095711, 16.98997739,  6.10122766,
       16.40395371, 26.8617578 , 28.65134873, 16.04152206, 31.05717438,
       24.94534041])

In [46]:
reg.coef_

array([-1.06837052e-01,  4.86447699e-02,  1.57318805e-03,  2.91139291e+00,
       -1.69474451e+01,  3.54158179e+00,  3.16870983e-04, -1.52284128e+00,
        3.17941719e-01, -1.28035057e-02, -9.20158709e-01,  9.49521159e-03,
       -5.71677402e-01])

In [61]:
from sklearn.metrics import mean_squared_error, r2_score

In [52]:
mean_squared_error(testy, py_pred)

26.390087176980074

In [62]:
lasso = linear_model.Lasso(alpha=1.0)

In [54]:
lasso.fit(trainx,trainy)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [55]:
y_pred = lasso.predict(testx)

In [56]:
y_pred

array([19.85178391, 13.67757127, 33.55788105, 28.55461773, 26.37537743,
       20.97570073, 11.9380175 , 26.84152994, 33.9686708 , 12.29644274,
       25.33394579, 24.35982871, 25.92530035, 10.40254929, 23.53541568,
       25.98698822, 14.80800631,  2.5411661 , 28.48911802, 25.44957669,
       24.08680335, 16.59812589, 33.71537044, 22.25593319,  0.69193176,
       30.71156764, 16.68686873, 20.52398832, 28.47740767, 15.19192203,
       11.25971437, 25.29957286, 28.18629004, 25.28299752, 25.52419738,
       31.04363468, 17.84923125, 33.00897101, 33.36984593, 26.6948473 ,
       28.34734701, 27.6669894 , 24.16280366, 17.2157685 ,  8.41857077,
       15.87388999, 24.05510092, 26.49384669, 17.56544654, 29.37821503,
       24.60001368])

In [57]:
lasso.coef_

array([-0.06628834,  0.05510682, -0.        ,  0.        , -0.        ,
        0.67657805,  0.01882272, -0.77092071,  0.28517945, -0.01602104,
       -0.6779322 ,  0.00842789, -0.80644415])

In [58]:
mean_squared_error(testy, y_pred)

34.10488791994309

In [68]:
lasso2= linear_model.Lasso(alpha=5.0)

In [69]:
lasso2.fit(trainx,trainy)

Lasso(alpha=5.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [65]:
y2_pred = lasso2.predict(testx)

In [70]:
y2_pred

array([19.95424669, 24.84080253, 26.33411603, 24.85996543, 10.17099224,
       12.30043929, 22.18993915, 20.39921708, 20.42095404, 34.82416145,
       10.50964556, 17.83619641, 31.31931352, 30.45119608, 30.28005266,
       23.06856232, 20.94219214, 31.40906634, 27.60167291, 17.81504295,
       10.67823911, 23.8520961 , 25.30467002, 12.84526803, 27.36980682,
       19.33394806, 30.63671365, 19.58194107, 24.65682473, 28.07379971,
       23.30747087, 29.88325149, 10.55801908, 26.83689627, 21.21571656,
       30.64981876, 22.01132067, 28.3416284 , 27.12980157, 27.86420504,
       21.45095537, 26.13666704, 26.61136446, 21.77467074, 27.69801482,
       25.33128031, 23.65331336, 25.03547461, 24.47606993, 30.6504916 ,
       26.13810317])

In [71]:
mean_squared_error(testy, y2_pred)

26.740806186010683

In [72]:
lasso2.coef_

array([-0.        ,  0.04816339, -0.        ,  0.        ,  0.        ,
        0.        ,  0.03164432, -0.        ,  0.        , -0.00760329,
       -0.        ,  0.00655979, -0.75241677])